const $=id=>document.getElementById(id);const user=localStorage.getItem('lf-user')||`user-${crypto.randomUUID().slice(0,8)}`;localStorage.setItem('lf-user',user);let thread=localStorage.getItem('lf-thread')||`thread-${crypto.randomUUID().slice(0,8)}`;localStorage.setItem('lf-thread',thread);let history=[],pendingRun='';$('thread').textContent=thread;
function add(text,cls='assistant'){const el=document.createElement('div');el.className=`msg ${cls}`;el.textContent=text;$('messages').appendChild(el);$('messages').scrollTop=$('messages').scrollHeight;return el}function trace(text){const el=document.createElement('div');el.className='trace';el.textContent=text;$('messages').appendChild(el)}
async function consume(res){const reader=res.body.getReader(),dec=new TextDecoder();let pending='',answerEl=null;while(true){const {value,done}=await reader.read();pending+=dec.decode(value||new Uint8Array(),{stream:!done});let i;while((i=pending.indexOf('\n\n'))>=0){const block=pending.slice(0,i);pending=pending.slice(i+2);let event='message',data='';for(const line of block.split('\n')){if(line.startsWith('event:'))event=line.slice(6).trim();if(line.startsWith('data:'))data+=line.slice(5).trim()}if(!data)continue;const p=JSON.parse(data);if(event==='run_started'||event==='run_resumed'){pendingRun=p.run_id;trace(`${event}: ${p.run_id}`)}else if(event==='answer'){if(!answerEl)answerEl=add('');answerEl.textContent=p.content||''}else if(event==='interrupt'){pendingRun=p.run_id;$('approval-text').textContent=p.message||'需要确认';$('approval').classList.remove('hidden');renderPlan(p.plan)}else if(event==='done'){if(!answerEl)answerEl=add(p.answer||'');history.push({role:'assistant',content:p.answer||''});$('status').textContent='完成';refreshPlan();refreshReminders()}else if(event==='error'){add(`错误：${p.message}`);$('status').textContent='失败'}else if(event==='retrieval'){const d=p.diagnostics||{};trace(`retrieve: ${p.mode} · vector=${d.vector_count||0} keyword=${d.keyword_count||0} fused=${d.fused_count||0} reranker=${d.reranker||'none'}`)}else if(event==='evidence_decision'){trace(`证据决策：${p.action} · ${p.reason||''}`)}else if(event==='tool_call'){trace(`联网工具调用：${p.tool} · ${p.query||''}`)}else if(event==='tool_result'){trace(`联网工具结果：${p.tool} · ${p.count||0} 条${p.error?' · '+p.error:''}`)}else{trace(`${p.node||event}: ${p.message||p.intent||p.quality||p.query||event}`)}}if(done)break}}
async function send(){const text=$('input').value.trim();if(!text)return;$('input').value='';add(text,'user');history.push({role:'user',content:text});$('status').textContent='运行中';const res=await fetch('/api/chat/stream',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({message:text,user_id:user,thread_id:thread,history:history.slice(-12)})});await consume(res)}
async function resume(approved){$('approval').classList.add('hidden');const res=await fetch('/api/runs/resume',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({run_id:pendingRun,thread_id:thread,approved})});await consume(res)}
async function upload(){const file=$('file').files[0];if(!file)return;const body=new FormData();body.append('user_id',user);body.append('file',file);$('status').textContent='索引中';const res=await fetch('/api/documents',{method:'POST',body});const p=await res.json();$('status').textContent=res.ok?`已导入 ${p.document.chunk_count} 个片段`:(p.detail||'上传失败');refreshDocs()}
async function restoreConversation(){try{const p=await fetch(`/api/threads/${encodeURIComponent(thread)}/messages?user_id=${encodeURIComponent(user)}&limit=50`).then(r=>r.json());history=(p.messages||[]).map(x=>({role:x.role,content:x.content}));for(const item of history)add(item.content,item.role==='user'?'user':'assistant')}catch{}}
async function refreshDocs(){const p=await fetch(`/api/documents?user_id=${encodeURIComponent(user)}`).then(r=>r.json());$('docs').innerHTML=(p.documents||[]).map(d=>`<div class="item">${escapeHtml(d.filename)} · ${d.chunk_count}块 · ${d.vector_status}</div>`).join('')||'暂无资料'}async function refreshPlan(){const p=await fetch(`/api/learning/plan?user_id=${encodeURIComponent(user)}`).then(r=>r.json());renderPlan(p.plan)}function renderPlan(p){$('plan').innerHTML=p?.items?.map(x=>`<div class="item">${x.done?'✓':x.day}. ${escapeHtml(x.topic)}</div>`).join('')||'尚未创建'}function escapeHtml(s){const e=document.createElement('span');e.textContent=s||'';return e.innerHTML}
async function refreshCapabilities(){try{const p=await fetch('/api/health').then(r=>r.json()),web=p.tools?.web_search||{},mcp=p.tools?.mcp_server||{};$('capabilities').innerHTML=`<div class="item">联网搜索 · Tavily · ${web.enabled?'已启用':'待配置 API Key'}</div><div class="item">MCP · ${escapeHtml(mcp.name||'learningflow-agent')} · ${escapeHtml(mcp.transport||'stdio')} · ${escapeHtml(mcp.http_endpoint||'/mcp')}<br/>${(mcp.tools||[]).map(escapeHtml).join(' · ')}</div>`}catch{$('capabilities').textContent='工具状态获取失败'}}
$('send').onclick=send;$('upload').onclick=upload;$('input').onkeydown=e=>{if((e.ctrlKey||e.metaKey)&&e.key==='Enter')send()};document.querySelectorAll('[data-approved]').forEach(b=>b.onclick=()=>resume(b.dataset.approved==='true'));refreshDocs();refreshPlan();refreshCapabilities();
async function createReminder(){const message=$('reminder-input').value.trim();if(!message)return;$('status').textContent='创建提醒中';const res=await fetch(`/api/reminders/from-text?user_id=${encodeURIComponent(user)}`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({message})});const p=await res.json();$('status').textContent=res.ok?'提醒已创建':(p.detail||'创建提醒失败');if(res.ok)$('reminder-input').value='';refreshReminders()}
async function refreshReminders(){try{const [r,n]=await Promise.all([fetch(`/api/reminders?user_id=${encodeURIComponent(user)}`).then(x=>x.json()),fetch(`/api/notifications?user_id=${encodeURIComponent(user)}&unread_only=true`).then(x=>x.json())]);$('reminders').innerHTML=(r.reminders||[]).map(x=>`<div class="item">${escapeHtml(x.message)}<br/>${escapeHtml(new Date(x.run_at).toLocaleString())} · ${escapeHtml(x.repeat)}</div>`).join('')||'暂无提醒';$('notifications').innerHTML=(n.notifications||[]).map(x=>`<div class="item"><b>${escapeHtml(x.title)}</b><br/>${escapeHtml(x.message)}</div>`).join('')}catch{$('reminders').textContent='提醒加载失败'}}
$('create-reminder').onclick=createReminder;refreshReminders();setInterval(refreshReminders,15000);
async function uploadSkill(){const file=$('skill-file').files[0];if(!file)return;const body=new FormData();body.append('user_id',user);body.append('file',file);$('status').textContent='安装 Skill 中';const res=await fetch('/api/skills',{method:'POST',body}),p=await res.json();$('status').textContent=res.ok?`Skill 已安装：${p.skill.name}`:(p.detail||'Skill 安装失败');refreshSkills()}
async function refreshSkills(){try{const p=await fetch(`/api/skills?user_id=${encodeURIComponent(user)}`).then(r=>r.json());$('skills').innerHTML=(p.skills||[]).map(x=>`<div class="item"><b>${escapeHtml(x.name)}</b> v${escapeHtml(x.version)} · ${x.enabled?'启用':'停用'}<br/>${escapeHtml(x.description)}<br/>tools: ${(x.allowed_tools||[]).map(escapeHtml).join(', ')||'none'}</div>`).join('')||'暂无 Skill'}catch{$('skills').textContent='Skill 加载失败'}}
$('upload-skill').onclick=uploadSkill;refreshSkills();restoreConversation();
