/**
 * Cross-process OAuth callback regression (PR review P1, round 2).
 *
 * generateAuthUrl persists the pending-login state to disk; the dashboard's
 * /oauth/callback receiver then broadcasts the callback URL to every daemon —
 * a DIFFERENT process from the one that generated the link. The structured
 * tryHandleCallbackUrl must therefore match states from the same sources
 * handleCallbackUrl consumes (memory OR the persisted file), not a
 * memory-only precheck.
 *
 * Simulated here with two module instances: instance A generates the link
 * (persisting the state), then vi.resetModules() gives us instance B with an
 * EMPTY in-memory pending map — B must still match via the disk fallback.
 *
 * Run:  pnpm vitest run test/user-token-cross-process-callback.test.ts
 */
import { describe, it, expect, vi, beforeEach, afterEach } from 'vitest';
import { mkdtempSync, rmSync } from 'node:fs';
import { join } from 'node:path';
import { tmpdir } from 'node:os';

let tempDir: string;

vi.mock('../src/config.js', () => ({
  config: {
    session: {
      get dataDir() { return tempDir; },
    },
  },
}));

vi.mock('../src/utils/logger.js', () => ({
  logger: { debug: vi.fn(), info: vi.fn(), warn: vi.fn(), error: vi.fn() },
}));

const APP_ID = 'cli_crossproc_app';
const APP_SECRET = 'secret';

beforeEach(() => {
  tempDir = mkdtempSync(join(tmpdir(), 'user-token-crossproc-'));
  vi.resetModules();
});

afterEach(() => {
  rmSync(tempDir, { recursive: true, force: true });
  vi.unstubAllGlobals();
});

describe('tryHandleCallbackUrl across module instances', () => {
  it('matches a disk-persisted state generated by another instance', async () => {
    // Instance A: generate the link (persists pending state to disk).
    const a = await import('../src/utils/user-token.js');
    const { state } = a.generateAuthUrl(APP_ID, APP_SECRET, 'feishu');

    // Instance B: fresh module — empty in-memory pending map.
    vi.resetModules();
    const b = await import('../src/utils/user-token.js');

    // Token exchange is stubbed to fail fast; what matters is that B MATCHED
    // the state (so the dashboard broadcast stops at this daemon) instead of
    // reporting matched:false against a perfectly valid persisted state.
    vi.stubGlobal('fetch', vi.fn(async () => ({ ok: false, status: 500 })) as any);

    const result = await b.tryHandleCallbackUrl(
      `http://127.0.0.1:9768/callback?code=test_code&state=${encodeURIComponent(state)}`,
    );
    expect(result).not.toBeNull();
    expect(result!.matched).toBe(true);
    expect(result!.ok).toBe(false); // exchange stub failed — matching is the contract
  });

  it('still reports matched:false for a state no instance ever generated', async () => {
    const b = await import('../src/utils/user-token.js');
    const result = await b.tryHandleCallbackUrl(
      'http://127.0.0.1:9768/callback?code=x&state=never_generated_state',
    );
    expect(result).not.toBeNull();
    expect(result!.matched).toBe(false);
  });
});
